[package]
name = "discord-mpd"
version = "0.1.0"
authors = ["Boris-Chengbiao Zhou <bobo1239@web.de>"]

[dependencies]
discord = { git = "https://github.com/SpaceManiac/discord-rs.git" }
byteorder = "1.2.1"
mpd = "0.0.12"
dotenv = "0.11.0"
rocket = "0.3.6"
env_logger = "0.5.6"
log = "0.4.1"
rocket_codegen = "0.3.6"
failure = "0.1.1"
itertools = "0.7.8"
bytecount = "0.3.1"
