[package]
name = "rusty-webradio"
version = "0.1.0"
authors = ["Boris-Chengbiao Zhou <bobo1239@web.de>"]

[dependencies]
discord = { git = "https://github.com/SpaceManiac/discord-rs.git" }
byteorder = "1.2.1"
mpd = "0.0.12"
dotenv = "0.11.0"
